apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  labels:
    app: rstudio-server
spec:
  type: ClusterIP
  selector:
    app: rstudio-server
  ports:
  - port: 8787
    targetPort: 8787
